### ISSUE TITLE
DeployTo - SourceApp error remains

### ISSUE THREAD

**Issue by mikemalloy-commscope** [Epinova/epinova-dxp-deployment#26] opened 2020-04-22 21:07 UTC
I am still getting the same error.
When editing the task the drop-down indicates: cms,commerce
But, I noticed that the YAML indicates: SourceApp: 'cms, commerce'

_Originally posted by @mikemalloy-commscope in https://github.com/Epinova/epinova-dxp-deployment/issues/24#issuecomment-618026378_

**Comment by ovelartelius** [comment] 2020-04-23 10:10
Do you mean that the markdown documentation indicates SourceApp: 'cms, commerce'? I found and updated the documentation/DeployTo.md. But I have not found anything in the yaml files. The yaml files is still hardcoded to only use 'cms' since I have not been able to test this for commerce yet.

**Comment by mikemalloy-commscope** [comment] 2020-04-23 11:45
When I have added the task in the Release pipeline and I click "View YAML"

![image](https://user-images.githubusercontent.com/32370762/80095824-3278f880-852e-11ea-860f-4622a13e3911.png)

**Comment by ovelartelius** [comment] 2020-04-24 14:22
Sorry, updated the titel/name. Now i should have updated the value. Will release v1.0.9 ASAP.

**Comment by ovelartelius** [comment] 2020-04-27 09:39
Now v1.0.9 is released and I can now see that is right:
steps:
- task: epinova-sweden.epinova-dxp-deploy-extension.dxp-deployto-buildtask.DxpDeployTo@1
  displayName: 'Deploy Integration to Preproduction'
  inputs:
    SourceEnvironment: Integration
    TargetEnvironment: Preproduction
    SourceApp: 'cms,commerce'

**Comment by arjun-nakkeeran** [comment] 2020-06-16 15:54
@ovelartelius, For some reason, I still get the error when deploying Cms and Commerce. We use the DeployTo task v1.1.1. And the error is:

`##[error]Cannot validate argument on parameter 'SourceApp'. The argument "cms,commerce" does not belong to the set "cms,commerce" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.`

**Comment by ovelartelius** [comment] 2020-06-16 21:47
Hi @arjun-nakkeeran 
Are you using YAML or classic task? If YAML, can you show the task config? If classic, take a picture of the settings for that task.
If you have the full log for the DeployTo task when it fails it would also help to search for the problem. 
Regards
Ove

**Comment by arjun-nakkeeran** [comment] 2020-06-17 05:55
@ovelartelius 
We are using the classic task And the yaml preview looks like below:
```
steps:
- task: epinova-sweden.epinova-dxp-deploy-extension.dxp-deployto-buildtask.DxpDeployTo@1
  displayName: 'Promote Integration to Preproduction'
  inputs:
    ClientKey: '$(DXP.ClientKey)'
    ClientSecret: '$(DXP.ClientSecret)'
    SourceEnvironment: Integration
    TargetEnvironment: Preproduction
    SourceApp: 'cms,commerce'
```

And the log for the DeployTo task:
```
2020-06-16T15:40:16.4263955Z ##[section]Starting: Promote Integration to Preproduction
2020-06-16T15:40:16.4414226Z ==============================================================================
2020-06-16T15:40:16.4414601Z Task         : Deploy To (Episerver DXP)
2020-06-16T15:40:16.4415028Z Description  : Start move DXP deploy from source environment to target environment. Like clicking on the 'Deploy To' button in PAAS. (Episerver DXP, former DXC)
2020-06-16T15:40:16.4415429Z Version      : 1.1.1
2020-06-16T15:40:16.4415648Z Author       : Ove Lartelius
2020-06-16T15:40:16.4416019Z Help         : https://github.com/Epinova/epinova-dxp-deployment/blob/master/documentation/DeployTo.md
2020-06-16T15:40:16.4416409Z ==============================================================================
2020-06-16T15:40:17.7824256Z Inputs:
2020-06-16T15:40:17.7838901Z ClientKey: ****
2020-06-16T15:40:17.7855803Z ClientSecret: **** (it is a secret...)
2020-06-16T15:40:17.7871383Z ProjectId: ****
2020-06-16T15:40:17.7892741Z SourceEnvironment: Integration
2020-06-16T15:40:17.7909383Z TargetEnvironment: Preproduction
2020-06-16T15:40:17.7924425Z SourceApp: cms,commerce
2020-06-16T15:40:17.7941475Z UseMaintenancePage: False
2020-06-16T15:40:17.7958757Z Timeout: 1800
2020-06-16T15:40:17.7981225Z IncludeBlob: False
2020-06-16T15:40:17.8002397Z IncludeDb: False
2020-06-16T15:40:17.9312852Z @{Version=5.1.17763.1007}
2020-06-16T15:40:35.1000673Z 
2020-06-16T15:40:35.3798968Z ##[error]Cannot validate argument on parameter 'SourceApp'. The argument "cms,commerce" does not belong to the set "cms,commerce" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
2020-06-16T15:40:35.4203064Z ##[section]Finishing: Promote Integration to Preproduction

```

**Comment by ruwen** [comment] 2020-06-17 08:31
I guess this line should convert the string cms,commerce to array. https://github.com/Epinova/epinova-dxp-deployment/blob/012be2405c146e98e87503d57f775590a92b912c/src/DeployTo/DeployTo.ps1#L51

**Comment by ovelartelius** [comment] 2020-06-17 08:57
We have been able to recreate the error @arjun-nakkeeran. Working on a fix. Thx for input @ruwen !

**Comment by ovelartelius** [comment] 2020-06-17 10:37
@arjun-nakkeeran I will make a release with version 1.4 now. I have no commerce project to test on. But tested and see that it still works for cms. So I have not done anything worse :) Please try when release v1.4 is live and give me a response how it works.

**Comment by arjun-nakkeeran** [comment] 2020-06-30 14:04
Thanks @ovelartelius. I missed the message. We got the version 1.4 now. But we haven't got the need to deploy commerce manager yet. So could't verify it. Will get back when things didn't work. Thanks for the quick fix by the way.

**Comment by ovelartelius** [comment] 2020-06-30 14:11
No problem @arjun-nakkeeran. Just contact me if you get any more problem. I would be happy if you could come back and verify that the fix work so we can close this issue :)

**Comment by ovelartelius** [comment] 2020-08-25 12:49
I have not heard anything for almost 2 month. I will close this bug. It is fixed.

**Closed as completed by ovelartelius** 2020-08-25 12:49 UTC
Labels: bug
